### ISSUE TITLE
找不到包github.com/kitex-contrib/opentracing

### ISSUE THREAD

**Issue by dierbei** [kitex-contrib/tracer-opentracing#9]
![image](https://user-images.githubusercontent.com/52097565/157162569-0077b08b-660e-4d42-902e-3ab1b939299d.png)

**Comment by simon0-o** [comment]
There is no such import as `github.com/kitex-contrib/opentracing` in [client.go](https://github.com/cloudwego/kitex-examples/blob/main/hello/client/main.go), please make sure you are using the official version of kitex-examples.

**Comment by dierbei** [comment]
Thanks.
